refactor of counting sort and all classes to safe memory
DanerSound/Search-Algorithms pull request #24
Opened 2018-03-04 17:50 UTC by DanerSound

I want to avoid a declaration of an array that only I use twice in code so I decide to try this refactor.
let me know if it could work.
in this way, the file "sorterAlgo" have 4 different prototypes.

2018-03-04 17:57 UTC, DanerSound commented
I tested the Counting sort, it works

2018-03-05 13:47 UTC, Wabri requested changes
eliminare il sorting con firma doppia

2018-03-05 13:47 UTC, Wabri commented on Search-algorithms/src/base/Counting_sort.java
> +	public Integer[] sorting(Integer[] arrayToBeOrder, Integer maxValue ){
integrare questa firma con il metodo sorting(array)

2018-03-05 13:47 UTC, Wabri commented on Search-algorithms/src/base/Counting_sort.java
>  		// TODO Auto-generated method stub
creare un algoritmo di ordinamento con 2 estremi

2018-03-05 13:47 UTC, Wabri commented on Search-algorithms/src/base/Counting_sort.java
>  		// TODO Auto-generated method stub
il ritorno nullo non ci deve essere

2018-03-06 21:17 UTC, DanerSound commented
merged in quickSortV2

2018-03-06 21:17 UTC, closed without merging

2018-03-08 13:46 UTC, Wabri reviewed
vale il commento fatto per la pull request mergiata #25